parameters:
- name: arch
  type: string
  values:
  - amd64
  - armhf
  - arm64
  default: amd64

- name: timeout
  type: number
  default: 60

- name: swss_artifact_name
  type: string

- name: swss_common_artifact_name
  type: string

- name: artifact_name
  type: string

- name: buildimage_artifact_name
  type: string
  default: 'sonic-buildimage.vs'

- name: buildimage_artifact_project
  type: string
  default: 'build'

- name: buildimage_artifact_pipeline
  type: string
  default: 'Azure.sonic-buildimage.official.vs'

- name: buildimage_artifact_branch
  type: string
  default: '$(BUILD_BRANCH)'

- name: sairedis_artifact_name
  type: string

- name: sairedis_artifact_project
  type: string
  default: 'build'

- name: sairedis_artifact_pipeline
  type: string
  default: 'Azure.sonic-sairedis'

- name: sairedis_artifact_branch
  type: string
  default: '$(BUILD_BRANCH)'

- name: sairedis_artifact_folder
  type: string
  default: '.'

- name: asan
  type: boolean
  default: false

- name: allow_failed_artifact
  type: boolean
  default: false

jobs:
- job:
  displayName: ${{ parameters.arch }}
  timeoutInMinutes: ${{ parameters.timeout }}

  pool:
    vmImage: 'ubuntu-20.04'

  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: Azure.sonic-swss-common
      artifact: ${{ parameters.swss_common_artifact_name }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/$(BUILD_BRANCH)'
      allowFailedBuilds: ${{ parameters.allow_failed_artifact }}
      path: $(Build.ArtifactStagingDirectory)/download
    displayName: "Download sonic swss common deb packages"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: ${{ parameters.sairedis_artifact_project }}
      pipeline: ${{ parameters.sairedis_artifact_pipeline }}
      artifact: ${{ parameters.sairedis_artifact_name }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/${{ parameters.sairedis_artifact_branch }}'
      path: $(Build.ArtifactStagingDirectory)/download/sairedis
      patterns: |
        ${{ parameters.sairedis_artifact_folder }}/libsaivs_*.deb
        ${{ parameters.sairedis_artifact_folder }}/libsaivs-dev_*.deb
        ${{ parameters.sairedis_artifact_folder }}/libsairedis_*.deb
        ${{ parameters.sairedis_artifact_folder }}/libsairedis-dev_*.deb
        ${{ parameters.sairedis_artifact_folder }}/libsaimetadata_*.deb
        ${{ parameters.sairedis_artifact_folder }}/libsaimetadata-dev_*.deb
        ${{ parameters.sairedis_artifact_folder }}/syncd-vs_*.deb
    displayName: "Download sonic sairedis deb packages"
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: ${{ parameters.swss_artifact_name }}
      path: $(Build.ArtifactStagingDirectory)/download
    displayName: "Download pre-stage built ${{ parameters.swss_artifact_name }}"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: ${{ parameters.buildimage_artifact_project }}
      pipeline: ${{ parameters.buildimage_artifact_pipeline }}
      artifact: ${{ parameters.buildimage_artifact_name }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/${{ parameters.buildimage_artifact_branch }}'
      path: $(Build.ArtifactStagingDirectory)/download
      patterns: '**/target/${{ parameters.artifact_name }}.gz'
    displayName: "Download sonic-buildimage ${{ parameters.artifact_name }}"
  - script: |
      set -ex
      echo $(Build.DefinitionName).$(Build.BuildNumber)

      docker load < $(Build.ArtifactStagingDirectory)/download/target/${{ parameters.artifact_name }}.gz

      mkdir -p .azure-pipelines/docker-sonic-vs/debs

      cp -v $(Build.ArtifactStagingDirectory)/download/sairedis/${{ parameters.sairedis_artifact_folder }}/*.deb .azure-pipelines/docker-sonic-vs/debs
      cp -v $(Build.ArtifactStagingDirectory)/download/*.deb .azure-pipelines/docker-sonic-vs/debs

      pushd .azure-pipelines

      build_args=""
      if [ '${{ parameters.asan }}' == True ]; then
        build_args="--build-arg need_dbg=y"
      fi

      docker build $build_args --no-cache -t docker-sonic-vs:$(Build.DefinitionName).$(Build.BuildNumber).asan-${{ parameters.asan }} docker-sonic-vs

      popd

      docker save docker-sonic-vs:$(Build.DefinitionName).$(Build.BuildNumber).asan-${{ parameters.asan }} | gzip -c > $(Build.ArtifactStagingDirectory)/docker-sonic-vs.gz
      rm -rf $(Build.ArtifactStagingDirectory)/download
    displayName: "Build ${{ parameters.artifact_name }}"
  - publish: $(Build.ArtifactStagingDirectory)/
    artifact: ${{ parameters.artifact_name }}
    displayName: "Archive sonic docker vs image"
